 
language: cpp
dist: xenial
compiler: 
  - g++-7
  - clang

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - cmake --version
  - mkdir build && cd build && cmake .. 
  - cmake --build . --config Debug
  - ctest -C Debug